server:
  port: 8888
mybatis:
  # 搜索指定包的别名
  type-aliases-package: com.gfxy.master.vo
  # 配置 mapper 的扫描
  mapper-locations: classpath:mapper/*.xml
  # 加载全局的配置文件
  config-location: classpath:mybatis/mybatis.xml
spring:
  profiles:
    active: druid

#  # 服务模块
#  devtools:
#    restart:
#      enabled: true  #设置开启热部署
#      additional-paths: src/main/java #重启目录
#      exclude: WEB-INF/**
#  freemarker:
#    cache: false    #页面不加载缓存，修改即时生效
debug: false

springdoc:
  swagger-ui:
    # 修改Swagger UI路径
    path: /swagger-ui.html
    # 开启Swagger UI界面
    enabled: true
  api-docs:
    # 修改api-docs路径
    path: /v3/api-docs
    # 开启api-docs
    enabled: true
  # 配置需要生成接口文档的扫描包
  packages-to-scan: com.gfxy.master.controller
  # 配置需要生成接口文档的接口路径
  paths-to-match: /**
